[package]
name = "source_control_rest_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.217", features = ["derive"] }
source_control_application = {path="../../../../applications/source_control"}
source_control_domain = {path="../../../../domains/source_control"}
source_control_postgres_persistence_adapter = {path="../../persistence/postgres"}
serde_json = "1.0.137"
tracing = {workspace = true}
shaku_actix = {workspace = true}

