version: '3.8'

services:
  # Grafana - Visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "8003:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
      - tempo
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - monitoring

  # Prometheus - Metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

  # Loki - Logs
  loki:
    image: grafana/loki:latest
    container_name: loki
    user: root  # Running as root for development
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  # Tempo - Traces
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    user: root  # Running as root for development
    ports:
      - "3200:3200"
    volumes:
      - ./tempo/tempo-config.yaml:/etc/tempo/tempo-config.yaml
      - tempo-data:/tmp/tempo
    command: -config.file=/etc/tempo/tempo-config.yaml
    networks:
      - monitoring

  # OpenTelemetry Collector (using contrib version)
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "8888:8888"   # Metrics
      - "8889:8889"   # Health check
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otelcol/config.yaml
    depends_on:
      - prometheus
      - loki
      - tempo
    command: ["--config=/etc/otelcol/config.yaml"]
    networks:
      - monitoring

volumes:
  grafana-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/.rafaeltab/volumes/source_control/grafana_data
  prometheus-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/.rafaeltab/volumes/source_control/prometheus_data
  loki-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/.rafaeltab/volumes/source_control/loki_data
  tempo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/.rafaeltab/volumes/source_control/tempo_data

networks:
  monitoring:
    driver: bridge

