[package]
name = "tracing_util"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-log = "0.2.0"
once_cell = { version = "*" }
tokio = { version = "1.0", features = ["full"] }
tracing = {workspace = true}
tracing-core = { version = "*" }
tracing-subscriber = { version = "*", features = ["env-filter","registry", "std"] }
log = {workspace = true}

tracing-opentelemetry = {workspace = true}
opentelemetry-stdout = {workspace = true}
opentelemetry-appender-log = {workspace = true}
opentelemetry = {workspace = true}
opentelemetry_sdk = {workspace = true}
opentelemetry-otlp = {workspace = true}
opentelemetry-semantic-conventions = {workspace = true}
