[package]
name = "tracing_util"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-log = "0.2.0"
once_cell = { version = "*" }
opentelemetry = { version = "*", features = ["metrics", "logs"] }
opentelemetry_sdk = { version = "*", features = ["rt-tokio", "logs"] }
opentelemetry-otlp = { version = "*", features = ["tonic", "metrics", "logs"] }
opentelemetry-semantic-conventions = { version = "*" }
tokio = { version = "1.0", features = ["full"] }
opentelemetry-appender-tracing = { version = "*", default-features = false}
tracing = {workspace = true}
tracing-core = { version = "*" }
tracing-subscriber = { version = "*", features = ["env-filter","registry", "std"] }
tracing-opentelemetry = "0.28.0"
opentelemetry-stdout = "0.27.0"
