[package]
name = "source_control_postgres_persistence_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"
eventstore = "3.0.0"
serde = "1.0.217"
serde_json = "1.0.135"
source_control_domain = {path= "../../../../domains/source_control"}
thiserror = "2.0.11"
tokio-postgres = "0.7.12"
tracing = {workspace = true}
shaku = {workspace = true}

