receivers:
  postgresql:
    endpoint: "postgres:5432"
    username: "source_control"
    password: "S3cret"
    collection_interval: 10s
    tls:
      insecure: true
      insecure_skip_verify: true
  prometheus:
    config:
      scrape_configs:
        - job_name: 'eventstoredb'
          scrape_interval: 10s
          static_configs:
            - targets: ['eventstore.db:2113']

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1000

exporters:
  otlp/tempo:
    endpoint: tempo:14317
    tls:
      insecure: true
  otlphttp:
    endpoint: http://loki:3100/otlp
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: otel

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp, postgresql, prometheus]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
