[package]
name = "event_store_util"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"
eventstore = "3.0.0"
log = {workspace = true}
serde = "1.0.217"
serde_json = "1.0.135"
source_control_domain = {path= "../../domains/source_control"}
